# Generated by Django 4.0.2 on 2023-10-22 23:43

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('Quran Memorization', 'Quran Memorization'), ('Quran Recictation with Tajweed', 'Quran Recictation with Tajweed'), ('Alim Course', 'Alim Course'), ('Hadith Course', 'Hadith Course'), ('Tafseer ul Quran', 'Tafseer ul Quran')], help_text='Course Name', max_length=40, verbose_name='Course Name')),
                ('course_image', models.ImageField(upload_to='course_images/')),
                ('language', models.CharField(choices=[('English', 'English'), ('Urdu', 'Urdu'), ('Arabic', 'Arabic')], help_text='Language', max_length=40, verbose_name='Language')),
                ('brief', froala_editor.fields.FroalaField()),
                ('price', models.FloatField(help_text='Price of Course', verbose_name='Price of Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_image', models.ImageField(upload_to='image/teacher/')),
                ('name', models.CharField(help_text="Teacher's Name", max_length=90, verbose_name='Teacher Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text="Teacher's Gender", max_length=10, verbose_name='Teacher Gender')),
                ('nationality', models.CharField(help_text="Teacher's Nationality", max_length=20, verbose_name='Teacher Nationality')),
                ('Bio', models.TextField(help_text='Bio of Teacher', max_length=700, verbose_name='Bio')),
                ('courses', models.ManyToManyField(to='main.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_image', models.ImageField(upload_to='image/student/')),
                ('name', models.CharField(help_text='Student Name', max_length=50, verbose_name='Student Name')),
                ('age', models.IntegerField(help_text="Student's age", verbose_name='Student age')),
                ('Teacher_language', models.CharField(help_text="student's chosen language", max_length=90, verbose_name="Student's Chosen Language")),
                ('start_time', models.TimeField(help_text='Student avaiable at that Time', verbose_name='Start Time')),
                ('end_time', models.TimeField(help_text='Student available time ended at', verbose_name='End Time')),
                ('course', models.ForeignKey(help_text='Student Selected Course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.courses', verbose_name='Student Chosen Course')),
            ],
        ),
    ]
