# Generated by Django 4.0.2 on 2023-10-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='eventimage/')),
                ('location', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=70)),
                ('time', models.TimeField()),
            ],
        ),
    ]
