# Generated by Django 4.0.2 on 2023-10-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='weeks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
