# Generated by Django 4.2.6 on 2023-10-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_student_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_remarks',
            field=models.TextField(blank=True, help_text="Student's Progress in Following Course - You hae to update it weekly.", null=True, verbose_name="How's Student Studying"),
        ),
    ]
