# Generated by Django 4.2.6 on 2023-11-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
