# Generated by Django 4.2.6 on 2023-11-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Student Paid The Fees ?'),
        ),
    ]
